### PR TITLE
Update RowDataPacket.js

### PR DESCRIPTION
**Pull request by ashwinks**
When using subqueries in select statements, there's no table which means the data would be omitted if using nestTables. This fix only appends data to table objects if there is a table name, otherwise it's appended to the root object.

### CODE REVIEW

**Comment by dougwilson** [comment]
Thank you so much, looks good! Can we get some tests to go along with the change as well :)?

**Comment by ashwinks** [comment]
Sure, will do. Can I add to the existing nestedTable test?

**Comment by dougwilson** [comment]
Adding to the existing tests, as long as it doesn't remove anything, if fine :)

**Comment by ashwinks** [comment]
Doug, I added tests but used the wrong account. Please see https://github.com/ashwinks/node-mysql/commit/c0a85e4ee322c2a9538391c37ed632f7437d36dd

**Pull request closed without merging**
