### PR TITLE
Amazon SSL for RDS 2015

### PR DESCRIPTION
**Pull request by winzig**
See http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.Rotation

### CODE REVIEW

**Comment by sourcec0de** [comment]
@winzig you beat me to it!!!!

**Comment by dougwilson** [comment]
I'm going to release this today.

**Comment by sidorares** [comment]
@dougwilson run few tests manually against fresh rds instance and it works ok

**Comment by dougwilson** [comment]
Nice! Merging now, then :)

**Comment by dougwilson** [comment]
P.S. do you know why there are lot of different ones now?

**Comment by sidorares** [comment]
no. curious as well

**Comment by dougwilson** [comment]
Cool. I'm examining the contents now to see what's inside.

**Comment by sidorares** [comment]
let me know what's inside as I'm going to update it in mysql2 as well

**Comment by dougwilson** [comment]
Looks like it's a root CA and then one cert for each of their datacenters all signed by that root CA. That means potentially we only need to actually add one cert instead of 9.

**Comment by dougwilson** [comment]
@sidorares do you have a RDS instance? Would you be willing to turn on the new certificate (step 3 in http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.Rotation) on your RDS and then try using this lib to connect using _only_ the following cert?
```
-----BEGIN CERTIFICATE-----
MIIEATCCAumgAwIBAgIBRTANBgkqhkiG9w0BAQUFADCBijELMAkGA1UEBhMCVVMx
EzARBgNVBAgMCldhc2hpbmd0b24xEDAOBgNVBAcMB1NlYXR0bGUxIjAgBgNVBAoM
GUFtYXpvbiBXZWIgU2VydmljZXMsIEluYy4xEzARBgNVBAsMCkFtYXpvbiBSRFMx
GzAZBgNVBAMMEkFtYXpvbiBSRFMgUm9vdCBDQTAeFw0xNTAyMDUyMjAzMTlaFw0y
MDAzMDUyMjAzMTlaMIGUMQswCQYDVQQGEwJVUzETMBEGA1UECAwKV2FzaGluZ3Rv
bjEQMA4GA1UEBwwHU2VhdHRsZTEiMCAGA1UECgwZQW1hem9uIFdlYiBTZXJ2aWNl
cywgSW5jLjETMBEGA1UECwwKQW1hem9uIFJEUzElMCMGA1UEAwwcQW1hem9uIFJE
UyBhcC1zb3V0aGVhc3QtMSBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBANaXElmSEYt/UtxHFsARFhSUahTf1KNJzR0Dmay6hqOXQuRVbKRwPd19u5vx
DdF1sLT7D69IK3VDnUiQScaCv2Dpu9foZt+rLx+cpx1qiQd1UHrvqq8xPzQOqCdC
RFStq6yVYZ69yfpfoI67AjclMOjl2Vph3ftVnqP0IgVKZdzeC7fd+umGgR9xY0Qr
Ubhd/lWdsbNvzK3f1TPWcfIKQnpvSt85PIEDJir6/nuJUKMtmJRwTymJf0i+JZ4x
7dJa341p2kHKcHMgOPW7nJQklGBA70ytjUV6/qebS3yIugr/28mwReflg3TJzVDl
EOvi6pqbqNbkMuEwGDCmEQIVqgkCAwEAAaNmMGQwDgYDVR0PAQH/BAQDAgEGMBIG
A1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFAu93/4k5xbWOsgdCdn+/KdiRuit
MB8GA1UdIwQYMBaAFE4C7qw+9hXITO0s9QXBj5yECEmDMA0GCSqGSIb3DQEBBQUA
A4IBAQBlcjSyscpPjf5+MgzMuAsCxByqUt+WFspwcMCpwdaBeHOPSQrXNqX2Sk6P
kth6oCivA64trWo8tFMvPYlUA1FYVD5WpN0kCK+P5pD4KHlaDsXhuhClJzp/OP8t
pOyUr5109RHLxqoKB5J5m1XA7rgcFjnMxwBSWFe3/4uMk/+4T53YfCVXuc6QV3i7
I/2LAJwFf//pTtt6fZenYfCsahnr2nvrNRNyAxcfvGZ/4Opn/mJtR6R/AjvQZHiR
bkRNKF2GW0ueK5W4FkZVZVhhX9xh1Aj2Ollb+lbOqADaVj+AT3PoJPZ3MPQHKCXm
xwG0LOLlRr/TfD6li1AfOVTAJXv9
-----END CERTIFICATE-----
```

**Comment by sidorares** [comment]
already killed it. I'll recreate from home in ~2hrs

**Comment by dougwilson** [comment]
Cool, I can wait :) :+1: I'm about to go to sleep, so I'll see your results in ~8 hours.

**Comment by sidorares** [comment]
Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
    at SecurePair.<anonymous> (/private/tmp/node-mysql-certup/lib/Connection.js:326:34)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)

**Comment by dougwilson** [comment]
Thanks, @sidorares , that's what I was afraid of. I need to fix the verification implementation here so it'll work in the future, but for now we'll just add all 9 certs.

**Pull request closed without merging**
