### PR TITLE
PoolCluster node remove method

### PR DESCRIPTION
**Pull request by MalyshevDmitry**
Added poolCluster.remove() method, which helps to remove nodes from cluster:

```js
// create
var poolCluster = mysql.createPoolCluster();

poolCluster.add(config); // anonymous group
poolCluster.add('MASTER', masterConfig);
poolCluster.add('SLAVE1', slave1Config);
poolCluster.add('SLAVE2', slave2Config);

// remove manually
poolCluster.remove('SLAVE2'); // By nodeId
poolCluster.remove('SLAVE*'); // By target group : SLAVE1-2

// event on manually removing (for each node)
poolCluster.on('removeManually', function (nodeId) {
  console.log('REMOVED MANUALLY NODE: ' + nodeId); // nodeId = SLAVE1
});

// event on auto removing (i.e. when connection was lost)
poolCluster.on('remove', function (nodeId) {
  console.log('REMOVED NODE : ' + nodeId); // nodeId = SLAVE1
});
```

### CODE REVIEW

**Comment by MalyshevDmitry** [comment]
Please check tests and merge PR asap. Thank you!

**Comment by dougwilson** [comment]
Awesome, thank you!

**Comment by jonathandelgado** [comment]
Awesome feature!

**Comment by MalyshevDmitry** [comment]
@dougwilson When do you plan to merge the PR? This feature is very important for the our project. We need to deploy source to a lot of servers ASAP. Thank you.

**Comment by dougwilson** [comment]
Soon, mainly after I reviewed it and feel comfortable about it. I will have to maintain this code in the future and will have to field all bug reports about said code, so I don't want to move in haste. If you need it ASAP, just set your `package.json` to simple be `"mysql": "MalyshevDmitry/node-mysql#c671c648"`

**Comment by MalyshevDmitry** [comment]
@dougwilson Ok, thank you!

**Pull request closed without merging**
