### PR TITLE
test(tests): Add more things to test in LOAD DATA INFILE tests

### PR DESCRIPTION
**Pull request by evansiroky**
Adding in more columns of varying types and tests to check validity of inserted data.

### CODE REVIEW

**Comment by dougwilson** [comment]
Thanks for the report. I have tracked this down to a regression in the packet writing with the new pool implementation. Will have this fixed in a jiffy!

**Comment by dougwilson** [comment]
@evansiroky, thanks again for reporting this! It is fixed in 2.11.1, which has been published to npm!

**Comment by evansiroky** [comment]
Thanks for providing a fix so quickly!

**Comment by dougwilson** [comment]
it's no problem at all!

**Pull request closed without merging**
